# Generated by Django 6.0.2 on 2026-02-04 17:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handoff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('assigned_to', models.CharField(default='Dad', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('drive_design_file_id', models.CharField(blank=True, max_length=200)),
                ('video_url', models.URLField(blank=True)),
                ('default_steps', models.JSONField(blank=True, help_text='List of step strings, overrides template steps if set.', null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='handoff.tasktemplate')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='handoff.recurringtask'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('recurring_task', 'due_date'), name='unique_recurring_task_per_day'),
        ),
    ]
