# Generated by Django 6.0.2 on 2026-02-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handoff', '0003_mockupslot_templateattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='drive_mockup_folder_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
