# Generated by Django 6.0.2 on 2026-02-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handoff', '0004_task_drive_mockup_folder_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_root_folder_id', models.CharField(blank=True, max_length=200)),
                ('drive_credentials_file_path', models.CharField(blank=True, max_length=500)),
                ('drive_token_file_path', models.CharField(blank=True, max_length=500)),
                ('drive_use_service_account', models.BooleanField(default=False)),
                ('drive_service_account_file_path', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
