# Generated by Django 6.0.2 on 2026-02-04 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handoff', '0005_appsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockupTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('background_drive_file_id', models.CharField(max_length=200)),
                ('overlay_drive_file_id', models.CharField(blank=True, max_length=200)),
                ('mask_drive_file_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mockup_templates', to='handoff.tasktemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
