# Generated by Django 6.0.2 on 2026-02-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handoff', '0006_mockuptemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='auto_generate_mockups',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='mockups_generated_design_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
