# Generated by Django 6.0.2 on 2026-02-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handoff', '0007_appsettings_auto_generate_mockups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockuptemplate',
            name='overlay_position',
            field=models.CharField(choices=[('OVER', 'Overlay above design'), ('UNDER', 'Overlay below design')], default='OVER', max_length=10),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='sample_design_drive_file_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
