# Generated by Django 6.0.2 on 2026-02-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handoff', '0008_mockuptemplate_overlay_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockuptemplate',
            name='design_height',
            field=models.PositiveIntegerField(default=4000),
        ),
        migrations.AddField(
            model_name='mockuptemplate',
            name='design_width',
            field=models.PositiveIntegerField(default=4000),
        ),
        migrations.AddField(
            model_name='mockuptemplate',
            name='design_x',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mockuptemplate',
            name='design_y',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
