# Generated by Django 6.0.2 on 2026-02-04 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handoff', '0009_mockuptemplate_design_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockupDesignBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('x', models.PositiveIntegerField(default=0)),
                ('y', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=4000)),
                ('height', models.PositiveIntegerField(default=4000)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_boxes', to='handoff.mockuptemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
