# Generated by Django 6.0.2 on 2026-02-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handoff', '0010_mockupdesignbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(unique=True)),
                ('drive_design_file_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
