# Generated by Django 6.0.2 on 2026-02-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handoff', '0011_scheduleddesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockupdesignbox',
            name='rotation',
            field=models.FloatField(default=0.0),
        ),
    ]
