# Generated by Django 6.0.2 on 2026-02-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handoff', '0020_storemembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateattachment',
            name='include_in_mockup_zip',
            field=models.BooleanField(default=True, help_text='Include this file in front-end mockup ZIP downloads.'),
        ),
    ]
