# Generated by Django 6.0.2 on 2026-02-07 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handoff", "0021_templateattachment_include_in_mockup_zip"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField()),
                ("author", models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="admin_notes", to=settings.AUTH_USER_MODEL)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
