# Generated by Django 6.0.2 on 2026-02-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handoff", "0022_adminnote"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminNoteImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("drive_file_id", models.CharField(max_length=200)),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="images", to="handoff.adminnote")),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
