# Generated by Django 6.0.2 on 2026-02-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handoff", "0024_adminnote_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminNoteFolder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="adminnote",
            name="folder",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="notes", to="handoff.adminnotefolder"),
        ),
    ]
