# Generated by Django 6.0.2 on 2026-02-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handoff', '0025_adminnote_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpublication',
            name='etsy_description',
            field=models.TextField(blank=True, default='', help_text='Optional Etsy description text scoped to this store.'),
        ),
    ]
